-- ==========================================
-- 1. Bridge Infrastructure & Traffic Data
-- ==========================================
-- This table stores the static PennDOT dataset 
-- for all 56,000+ bridges in Pennsylvania.

CREATE TABLE IF NOT EXISTS bridge_traffic_stats (
    brkey TEXT PRIMARY KEY,           -- Unique bridge identifier
    location TEXT,                    -- General location description
    facility TEXT,                    -- The road/feature carried by the bridge
    adttotal INTEGER,                 -- Average Daily Traffic
    truckpct NUMERIC(5, 2),           -- Percentage of ADT that is truck traffic
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing for faster dashboard searches by location
CREATE INDEX IF NOT EXISTS idx_bridge_location ON bridge_traffic_stats (location);

-- ==========================================
-- 2. State Fuel Benchmarks
-- ==========================================
-- This table stores the automated AAA state averages.
-- Using .insert() in the worker allows for a 
-- historical log of price fluctuations.

CREATE TABLE IF NOT EXISTS state_fuel_benchmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gas_price NUMERIC(5, 3),          -- AAA Gas Benchmark ($X.XXX)
    diesel_price NUMERIC(5, 3),       -- AAA Diesel Benchmark ($X.XXX)
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing for fast retrieval of the most recent price
CREATE INDEX IF NOT EXISTS idx_fuel_updated_at ON state_fuel_benchmarks (updated_at DESC);